### ISSUE TITLE
[JOSS Review]: Recommendation for use of inheritance

### ISSUE THREAD

**Issue by s-goldman** [Magritte-code/pomme#11]
In the future, if you are ever planning on further developing the models, you may want to look into using inheritance. By using a base class (e.g. General Model) and additional classes that import that base class, you can avoid needing to have the same class method defined for each class. 

This is not a requirement of the review, but merely a suggestion. Feel free to close this issue after reading it. 

If you intend to continue developing this code I would also urge you to adopt a test-driven development strategy. It is a time saver in the long run and you could use some more bite-sized unit tests.

**Comment by FredDeCeuster** [comment]
I completely agree! I plan to refactor the model class in a next iteration of the code, and indeed more (unit) tests would be better.
