### ISSUE TITLE
[JOSS Review]: Installation on Mac ARM64 (M1 chip) 

### ISSUE THREAD

**Issue by s-goldman** [Magritte-code/pomme#9]
When I try to install the package with conda on my macbook with an M1 chip, conda doesn't seem to be able to find the package. I'm guessing this is because conda only has the OSX (intel chip) distribution. 

The pip install does work. 

This is not necessarily a problem, but it may be useful to describe what platforms are currently supported (maybe in the readme?).

**Comment by FredDeCeuster** [comment]
Indeed, for now, we won't support ARM-based chips.
I've added this to the README.md
